package com.kyriakospatsias;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;


@DynamoDBTable(tableName = "Memorandum-notes")
public class Note {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String noteId;
    private String title;
    private String body;

    public Note(){

    }

    public Note(String title, String body) {
        this.title = title;
        this.body = body;
    }

    public String getNoteId() {
        return noteId;
    }

    public void setNoteId(String noteId) {
        this.noteId = noteId;
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @DynamoDBAttribute
    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    @Override
    public String toString() {
        return "Note{" +
                "id=" + noteId +
                ", title='" + title + '\'' +
                ", body='" + body + '\'' +
                '}';
    }
}
