plugins {
    id 'org.springframework.boot' version '3.2.1'
    id 'io.spring.dependency-management' version '1.1.4'
    id 'java'
}

apply plugin: 'java'
apply plugin: 'idea'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'

group='com.kyriakospatsias'
version='1.3-SNAPSHOT'

sourceCompatibility = '17' // Specify Java 17 for Spring Boot 3.2

repositories {
    mavenCentral()
}

/*dependencyManagement {
    imports {
        mavenBom 'software.amazon.awssdk:bom:2.22.2'
    }
}*/

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-oauth2-resource-server")
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation 'com.h2database:h2'
    //implementation 'org.springframework.data:spring-data-jdbc'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.postgresql:postgresql:42.7.1'
    implementation 'org.testcontainers:postgresql:1.19.3'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.13.1'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.security:spring-security-test'
}

test {
    useJUnitPlatform()
}

// This section causes useful test output to go to the terminal.
test.testLogging {
    events "passed", "skipped", "failed" //, "standardOut", "standardError"
    showExceptions = true
    exceptionFormat = "full"
    showCauses = true
    showStackTraces = true
    // Change to `true` for more verbose test output
    showStandardStreams = false
}