server:
  port: 8082

spring:
  jpa:
    generate-ddl: false
  hibernate:
    ddl-auto: update
  datasource:
    url: jdbc:h2:/opt/Memorandum/data/memorandumDb
  h2:
    console:
      enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_TKuvDF3uW