server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_TKuvDF3uW
          jwk-set-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_TKuvDF3uW/.well-known/jwks.json
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/memorandum
    username: postgres
    password: mysecretpassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

# CLI option -Pargs=--logging.level.org.springframework=INFO,--logging.level.com.kyriakospatsias=DEBUG
logging:
  level:
    root: INFO
    com:
      kyriakospatsias: DEBUG