server:
  port: 8080

spring:
  jpa:
    generate-ddl: false
  hibernate:
    ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_TKuvDF3uW

amazon:
  dynamodb:
    endpoint: dynamodb.us-west-2.amazonaws.com
  aws:
    accesskey: AKIA34N57244PMRUYUFD
    secretkey: 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