server:
  port: 8080

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_TKuvDF3uW
  main:
    allow-bean-definition-overriding: true

amazon:
  dynamodb:
    endpoint: dynamodb.us-west-2.amazonaws.com
  aws:
    accesskey: ${AWS_ACCESS_KEY}
    secretkey: ${AWS_SECRET_KEY}


# CLI option -Pargs=--logging.level.org.springframework=INFO,--logging.level.com.kyriakospatsias=DEBUG
logging:
  level:
    root: INFO
    com:
      kyriakospatsias: DEBUG